"""Content for the interactive tutorial (`/tutorial`, `tutorial/offline.html`).

Additive, non-core feature: it never calls `app.services`, never touches the
database, and is not part of the spec §12 acceptance suite. Every "click" in
the tutorial advances a scripted step; nothing here executes a real booking,
preemption, invitation, or deletion.

`TUTORIAL_STEPS` is the single source of truth for content, shared by both
delivery modes (the served `/tutorial` page and the standalone
`tutorial/offline.html` file generated by `manage.py tutorial-build`). Real
UI copy is always pulled from `app.i18n.en`'s catalogue -- via the `*_key`
convention in `_resolve()` for the handful of fields reused across many
steps (form field labels, notices, legends), or via `_t()` inline for
everything else -- so a renamed string key breaks loudly here instead of
silently drifting from the real screens it mirrors. Illustrative sample data
(names, times, room contents) is authored directly since it has no real
counterpart to drift from.

Each demo section that is reached by clicking somewhere in the site's
navigation opens with a `nav_click` bridge step (see `_nav_click_step()`)
that shows exactly which nav item was clicked to get there, before diving
into that section's content -- a step landing on a screen "out of nowhere"
was confusing to follow.
"""

from __future__ import annotations

from app.i18n.en import STRINGS as _EN

TRACKS = ("member", "admin")


def _text(key: str) -> str:
    return _EN[key]


def _t(key: str, **params: object) -> str:
    """Resolve an `app.i18n.en` string, formatting it if params are given."""
    text = _EN[key]
    return text.format(**params) if params else text


def _resolve(step: dict) -> dict:
    data = step["screen_data"]
    resolved = dict(data)
    if "fields" in data:
        fields = []
        for f in data["fields"]:
            field = {"label": _text(f["key"]), "type": f.get("type", "text")}
            if "value" in f:
                field["value"] = f["value"]
            if "help_key" in f:
                field["help"] = _text(f["help_key"])
            fields.append(field)
        resolved["fields"] = fields
    if "submit_key" in data:
        resolved["submit_label"] = _text(data["submit_key"])
    if "message_key" in data:
        resolved["message"] = _text(data["message_key"])
    if "banner_key" in data:
        resolved["banner"] = _text(data["banner_key"])
    if "notice_key" in data:
        resolved["notice"] = _text(data["notice_key"])
    if "legend" in data:
        resolved["legend"] = [_text(k) for k in data["legend"]]
    return {**step, "screen_data": resolved}


# A recurring fictional room and colleague, reused across steps so the whole
# walkthrough reads as one continuous story instead of disconnected demos.
_ROOM = "Meeting Room 1"
_COLLEAGUE = "Alex Wang"
_COLLEAGUE_DEPT = "Sales"

# Nav label sets, matching app/web/layout.py's _nav_items() and
# app/web/pages/admin_pages.py's _ADMIN_NAV exactly, so a "click here" bridge
# step always lists the same items in the same order as the real nav.
# The tutorial link sits last in every variant, and for an admin it comes
# after "Admin" -- so these cannot be built by appending to one another.
_HEADER_LOGGED_OUT = [_t("nav.login"), _t("nav.register"), _t("nav.tutorial")]
_MEMBER_CORE = [
    _t("nav.day"), _t("nav.week"), _t("nav.my_bookings"), _t("nav.account"),
]
_HEADER_MEMBER = _MEMBER_CORE + [_t("nav.tutorial")]
_HEADER_ADMIN = _MEMBER_CORE + [_t("nav.admin"), _t("nav.tutorial")]
_ADMIN_SUBNAV = [
    _t("admin.nav.dashboard"), _t("admin.nav.approvals"), _t("admin.nav.members"),
    _t("admin.nav.invitations"), _t("admin.nav.rooms"), _t("admin.nav.closures"),
    _t("admin.nav.bookings"), _t("admin.nav.preemptions"), _t("admin.nav.settings"),
    _t("admin.nav.emails"), _t("admin.nav.audit"),
]


def _nav_click_step(step_id: str, track: str, labels: list[str], highlight: str, caption: str) -> dict:
    """A bridge screen: the nav bar with exactly one item clickable.

    Inserted before a section's first content step so a viewer sees where a
    page came from instead of landing on it out of nowhere.
    """
    return {
        "id": step_id,
        "track": track,
        "caption": caption,
        "screen": "nav_click",
        "screen_data": {
            "items": [{"label": label, "hotspot": label == highlight} for label in labels],
        },
    }


_RAW_STEPS = [
    # --- registration ---------------------------------------------------
    {
        "id": "register-form",
        "track": "member",
        "caption": "Fill in your email, a password, and a few basic details to register.",
        "screen": "field_form",
        "screen_data": {
            "fields": [
                {"key": "auth.field.email", "type": "email"},
                {"key": "auth.field.password", "type": "password"},
                {"key": "auth.field.full_name", "type": "text"},
                {"key": "auth.field.department", "type": "text"},
                {"key": "auth.field.phone", "type": "text"},
            ],
            "submit_key": "auth.register.submit",
        },
    },
    {
        "id": "register-submitted",
        "track": "member",
        "caption": "The system always shows the same message here, whether or not "
                   "this email already has an account — it never confirms or denies.",
        "screen": "notice_panel",
        "screen_data": {"message_key": "auth.register.success", "kind": "success"},
    },
    {
        "id": "register-verified",
        "track": "member",
        "caption": "Clicking the verification link in the email lands here.",
        "screen": "notice_panel",
        "screen_data": {"message_key": "auth.verify.success", "kind": "success"},
    },
    # --- site orientation: the first thing you actually see -------------
    {
        "id": "orientation-header",
        "track": "member",
        "caption": "Before diving into any one feature — this header sits at "
                   "the top of every page. Day overview, Week view, My "
                   "bookings and Account are always there; an Admin console "
                   "link only shows up if you're an admin.",
        "screen": "header_preview",
        "screen_data": {
            "brand": _t("app.name"),
            "nav_items": _HEADER_MEMBER,
            "admin_item": _t("nav.admin"),
            "account_name": "You",
            "logout_label": _t("nav.logout"),
            "language_label": _t("nav.language"),
        },
    },
    {
        "id": "orientation-day-calendar",
        "track": "member",
        "caption": "And this is the main day view — every room's availability "
                   "for one day, side by side. The rest of this walkthrough "
                   "keeps coming back to this page.",
        "screen": "day_overview",
        "screen_data": {
            "date_label": "Tue, Sep 1",
            "prev_label": _t("day.prev"),
            "today_label": _t("day.today"),
            "next_label": _t("day.next"),
            "legend": ["day.legend.mine", "day.legend.other", "day.legend.free"],
            "jump_label": _t("day.jump_to_room"),
            "rooms": [
                {"name": "Meeting Room 1", "slots": [
                    {"time": "09:00–09:30", "kind": "free"},
                    {"time": "09:30–10:00", "kind": "other", "detail": "Standup"},
                ]},
                {"name": "Meeting Room 2", "slots": [
                    {"time": "09:00–09:30", "kind": "free"},
                    {"time": "09:30–10:00", "kind": "mine", "detail": "1:1"},
                ]},
            ],
        },
    },
    {
        "id": "register-pending",
        "track": "member",
        "caption": "One state worth calling out on that same page: you can log "
                   "in and browse read-only right away, but booking stays "
                   "locked until an admin approves your account.",
        "screen": "day_grid_readonly",
        "screen_data": {
            "banner_key": "error.AWAITING_APPROVAL",
            "legend": ["day.legend.mine", "day.legend.other", "day.legend.free"],
        },
    },
    # --- invitation-link registration: skips verification and approval --
    {
        "id": "invite-form",
        "track": "member",
        "caption": "An admin-issued invitation link works differently: the email "
                   "is already confirmed and locked, so there's no verification "
                   "step and no waiting for approval.",
        "screen": "field_form",
        "screen_data": {
            "notice_key": "auth.invite.intro",
            "fields": [
                {"key": "auth.field.email", "type": "email", "value": "sam@example.com"},
                {"key": "auth.field.password", "type": "password"},
                {"key": "auth.field.full_name", "type": "text"},
                {"key": "auth.field.department", "type": "text"},
                {"key": "auth.field.phone", "type": "text"},
            ],
            "submit_key": "auth.invite.submit",
        },
    },
    {
        "id": "invite-active",
        "track": "member",
        "caption": "That's it — the account is active immediately, and you're "
                   "signed straight into the day view, ready to book.",
        "screen": "notice_panel",
        "screen_data": {"message": "Your account is now active.", "kind": "success"},
    },
    # --- login / password recovery ---------------------------------------
    _nav_click_step(
        "bridge-login", "member", _HEADER_LOGGED_OUT, _t("nav.login"),
        "Every page has this header when you're signed out. Click "
        "“" + _t("nav.login") + "” to continue.",
    ),
    {
        "id": "login-form",
        "track": "member",
        "caption": "Logging in only needs your email and password.",
        "screen": "field_form",
        "screen_data": {
            "fields": [
                {"key": "auth.field.email", "type": "email"},
                {"key": "auth.field.password", "type": "password"},
            ],
            "submit_key": "auth.login.submit",
        },
    },
    {
        "id": "forgot-form",
        "track": "member",
        "caption": "Forgotten your password? Just the email address — there's a "
                   "link to this on the login page itself.",
        "screen": "field_form",
        "screen_data": {
            "fields": [{"key": "auth.field.email", "type": "email"}],
            "submit_key": "auth.forgot.submit",
        },
    },
    {
        "id": "forgot-success",
        "track": "member",
        "caption": "Same rule as registration: this message never confirms or "
                   "denies whether the address has an account.",
        "screen": "notice_panel",
        "screen_data": {"message_key": "auth.forgot.success", "kind": "success"},
    },
    {
        "id": "reset-form",
        "track": "member",
        "caption": "The link in that email leads here — pick a new password.",
        "screen": "field_form",
        "screen_data": {
            "fields": [
                {"key": "auth.field.new_password", "type": "password"},
                {"key": "auth.field.confirm_password", "type": "password"},
            ],
            "submit_key": "auth.reset.submit",
        },
    },
    {
        "id": "reset-success",
        "track": "member",
        "caption": "Password changed — log in with it from here on.",
        "screen": "notice_panel",
        "screen_data": {"message_key": "auth.reset.success", "kind": "success"},
    },
    {
        "id": "forced-password-change",
        "track": "member",
        "caption": "One special case: an account created from a temporary "
                   "password (like a freshly seeded admin) is forced through "
                   "this screen — not clicked into, redirected into — before "
                   "it can do anything else.",
        "screen": "field_form",
        "screen_data": {
            "notice_key": "auth.password.forced_notice",
            "fields": [
                {"key": "auth.field.current_password", "type": "password"},
                {"key": "auth.field.new_password", "type": "password"},
                {"key": "auth.field.confirm_password", "type": "password"},
            ],
            "submit_key": "auth.password.submit",
        },
    },
    # --- booking a free slot ----------------------------------------------
    _nav_click_step(
        "bridge-day-overview", "member", _HEADER_MEMBER, _t("nav.day"),
        "Back to the day view to actually book something — click "
        "“" + _t("nav.day") + "”.",
    ),
    {
        "id": "book-pick-start",
        "track": "member",
        "caption": "Every room's day is shown in 30-minute slots — some free, some "
                   "already booked by you or by others. Click “Book” on any "
                   "free slot to start.",
        "screen": "day_grid_interactive",
        "screen_data": {
            "hint": _t("day.hint_pick_start"),
            "room": _ROOM,
            "legend": ["day.legend.mine", "day.legend.other", "day.legend.free"],
            "slots": [
                {"time": "13:30–14:00", "kind": "other",
                 "detail": f"Weekly sync ・ {_COLLEAGUE}"},
                {"time": "14:00–14:30", "kind": "free", "action_label": _t("day.pick_start")},
                {"time": "14:30–15:00", "kind": "free"},
                {"time": "15:00–15:30", "kind": "mine", "detail": "1:1 ・ You"},
            ],
        },
    },
    {
        "id": "book-closed-slot",
        "track": "member",
        "caption": "Some slots are shut by an administrator — a cleaning "
                   "window, maintenance, an all-hands. They say why, and they "
                   "cannot be booked. A booking cannot run across one either, "
                   "so the slots past it stop offering an end time.",
        "screen": "day_grid_interactive",
        "screen_data": {
            "hint": _t("day.hint_pick_start"),
            "room": _ROOM,
            "legend": [
                "day.legend.mine", "day.legend.other", "day.legend.free",
                "day.legend.closed",
            ],
            "slots": [
                {"time": "11:30–12:00", "kind": "free",
                 "action_label": _t("day.pick_start")},
                {"time": "12:00–12:30", "kind": "closed",
                 "closed_label": _t("day.slot_closed"), "detail": "Deep clean"},
                {"time": "12:30–13:00", "kind": "closed",
                 "closed_label": _t("day.slot_closed"), "detail": "Deep clean"},
                {"time": "13:00–13:30", "kind": "free",
                 "action_label": _t("day.pick_start")},
            ],
        },
    },
    {
        "id": "book-pick-end",
        "track": "member",
        "caption": "The second click sets when it ends. You can only pick up to the "
                   "room's maximum booking length.",
        "screen": "day_grid_interactive",
        "screen_data": {
            "hint": _t("day.selected", time="14:00", room=_ROOM),
            "room": _ROOM,
            "slots": [
                {"time": "14:00–14:30", "kind": "start", "detail": "Start"},
                {
                    "time": "14:30–15:00", "kind": "free",
                    "action_label": _t("day.end_here", duration=_t("day.duration_hours", hours=1)),
                },
            ],
        },
    },
    {
        "id": "book-confirm-subject",
        "track": "member",
        "caption": "Give the meeting a title — pick a preset or type your own — "
                   "then submit.",
        "screen": "booking_form",
        "screen_data": {
            "summary": {"room": _ROOM, "time": "14:00–15:00", "duration": "1 hr"},
            "change_time_label": _t("book.change_time"),
            "pick_subject_label": _t("book.pick_subject"),
            "presets": ["Weekly sync", "1:1", "Project review"],
            "custom_label": _t("book.custom"),
            "custom_placeholder": _t("book.custom_placeholder"),
            "submit_label": _t("book.submit"),
        },
    },
    {
        "id": "book-success",
        "track": "member",
        "caption": "Because no one else held this slot, the booking is created "
                   "immediately — no extra confirmation needed. That confirmation "
                   "step only appears when you'd be overriding someone else's "
                   "existing booking.",
        "screen": "notice_panel",
        "screen_data": {"message_key": "my.booked_success", "kind": "success"},
    },
    {
        "id": "book-upcoming",
        "track": "member",
        "caption": "It now appears under My bookings, where you can cancel it any "
                   "time before it starts.",
        "screen": "table_list",
        "screen_data": {
            "heading": _t("my.upcoming"),
            "columns": [_t("my.room"), _t("my.title_col"), _t("my.time"), ""],
            "rows": [
                {
                    "cells": [_ROOM, "Weekly sync", "14:00–15:00"],
                    "actions": [{"label": _t("my.cancel")}],
                },
            ],
        },
    },
    # --- overriding someone else's booking (preemption) -------------------
    {
        "id": "preempt-pick-slot",
        "track": "member",
        "caption": f"Still on the day view — now suppose the 14:00 slot is "
                   f"already held by {_COLLEAGUE}, who has a lower priority "
                   "level than you. It's still shown as clickable — the "
                   "system decides whether you're allowed to take it only "
                   "after you try.",
        "screen": "day_grid_interactive",
        "screen_data": {
            "hint": _t("day.hint_pick_start"),
            "room": _ROOM,
            "slots": [
                {"time": "14:00–14:30", "kind": "other",
                 "detail": f"Team sync ・ {_COLLEAGUE}",
                 "action_label": _t("day.pick_start")},
                {"time": "14:30–15:00", "kind": "other",
                 "detail": f"Team sync ・ {_COLLEAGUE}"},
            ],
        },
    },
    {
        "id": "preempt-warning",
        "track": "member",
        "caption": "Because your level is higher, the system offers to override "
                   "it instead of blocking you — but it always names exactly "
                   "who and what would be cancelled first, right here.",
        "screen": "booking_form",
        "screen_data": {
            "warning": {
                "title": _t("book.will_override_title"),
                "message": _t("book.will_override", count=1),
                "victims": [f"{_ROOM} ・ 14:00–15:00 ・ {_COLLEAGUE}（{_COLLEAGUE_DEPT}）"],
            },
            "summary": {"room": _ROOM, "time": "14:00–15:00", "duration": "1 hr"},
            "change_time_label": _t("book.change_time"),
            "pick_subject_label": _t("book.pick_subject"),
            "presets": ["Weekly sync", "1:1", "Project review"],
            "custom_label": _t("book.custom"),
            "custom_placeholder": _t("book.custom_placeholder"),
            "submit_label": _t("book.submit_override"),
        },
    },
    {
        "id": "preempt-confirm",
        "track": "member",
        "caption": "This is the second, explicit confirmation the spec requires "
                   "before anything is actually cancelled — a plain \"submit\" "
                   "was never enough on its own.",
        "screen": "confirm_dialog",
        "screen_data": {
            "message": _t("booking.confirm.message", count=1),
            "victims": [f"{_ROOM} ・ 14:00–15:00 ・ {_COLLEAGUE}（{_COLLEAGUE_DEPT}）"],
            "submit_label": _t("booking.confirm.submit"),
            "cancel_label": _t("booking.confirm.cancel"),
            "danger": True,
        },
    },
    {
        "id": "preempt-success",
        "track": "member",
        "caption": f"The room is now yours. {_COLLEAGUE} gets an email saying "
                   "their booking was cancelled and naming the room and time — "
                   "but never who took it.",
        "screen": "notice_panel",
        "screen_data": {"message_key": "my.booked_success", "kind": "success"},
    },
    {
        "id": "preempt-displaced-view",
        "track": "member",
        "caption": f"From {_COLLEAGUE}'s side: the booking moves into their "
                   "history, tagged as overridden. Rebooking is on them — the "
                   "system doesn't do it automatically.",
        "screen": "table_list",
        "screen_data": {
            "heading": _t("my.past"),
            "columns": [_t("my.room"), _t("my.title_col"), _t("my.time"), _t("my.status")],
            "rows": [
                {
                    "cells": [_ROOM, "Team sync", "14:00–15:00"],
                    "status": {"text": _t("booking_status.preempted"), "tag_class": "tag-preempted"},
                },
            ],
        },
    },
    # --- cancelling your own booking ---------------------------------------
    _nav_click_step(
        "bridge-my-bookings", "member", _HEADER_MEMBER, _t("nav.my_bookings"),
        "To cancel a booking, start from the header — click "
        "“" + _t("nav.my_bookings") + "”.",
    ),
    {
        "id": "cancel-open",
        "track": "member",
        "caption": "Cancelling your own booking is one click from here, any "
                   "time before it starts.",
        "screen": "table_list",
        "screen_data": {
            "heading": _t("my.upcoming"),
            "columns": [_t("my.room"), _t("my.title_col"), _t("my.time"), ""],
            "rows": [
                {
                    "cells": [_ROOM, "Weekly sync", "14:00–15:00"],
                    "actions": [{"label": _t("my.cancel"), "hotspot": True, "danger": True}],
                },
            ],
        },
    },
    {
        "id": "cancel-success",
        "track": "member",
        "caption": "The slot is freed up immediately for anyone else to book.",
        "screen": "notice_panel",
        "screen_data": {"message_key": "my.cancelled_success", "kind": "success"},
    },
    # ======================================================================
    # Admin track
    # ======================================================================
    {
        "id": "admin-forced-password",
        "track": "admin",
        "caption": "The seeded admin account's initial password lives in a "
                   "deploy secret, so its very first login is forced through "
                   "this same screen before anything else is reachable.",
        "screen": "field_form",
        "screen_data": {
            "notice_key": "auth.password.forced_notice",
            "fields": [
                {"key": "auth.field.current_password", "type": "password"},
                {"key": "auth.field.new_password", "type": "password"},
                {"key": "auth.field.confirm_password", "type": "password"},
            ],
            "submit_key": "auth.password.submit",
        },
    },
    _nav_click_step(
        "bridge-admin-console", "admin", _HEADER_ADMIN, _t("nav.admin"),
        "An admin sees one extra link in the same header — "
        "“" + _t("nav.admin") + "”.",
    ),
    {
        "id": "admin-dashboard",
        "track": "admin",
        "caption": "The dashboard is the admin's landing page — pending work "
                   "and system health at a glance, including whether the "
                   "reminder cron job is actually still running.",
        "screen": "dashboard_panel",
        "screen_data": {
            "title": _t("admin.dashboard.title"),
            "stats": [
                {"label": _t("admin.dashboard.pending_approvals"),
                 "value": _t("admin.dashboard.pending_approvals_help", count=2)},
                {"label": _t("admin.dashboard.emails_today"),
                 "value": _t("admin.dashboard.emails_today_value", sent=14, cap=200)},
                {"label": _t("admin.dashboard.cron_title"),
                 "value": _t("admin.dashboard.cron_ok", when="2026-08-28 13:15",
                              status=_t("admin.dashboard.cron_status_ok"))},
            ],
        },
    },
    _nav_click_step(
        "bridge-approvals", "admin", _ADMIN_SUBNAV, _t("admin.nav.approvals"),
        "The admin console has its own row of tabs below the header. Click "
        "“" + _t("admin.nav.approvals") + "”.",
    ),
    {
        "id": "admin-approvals",
        "track": "admin",
        "caption": "New registrations wait here. Approve makes the account "
                   "active immediately; reject needs no reason — it's a "
                   "single click either way.",
        "screen": "table_list",
        "screen_data": {
            "heading": _t("admin.approvals.title"),
            "columns": [
                _t("admin.approvals.col_name"), _t("admin.approvals.col_department"),
                _t("admin.approvals.col_phone"), _t("admin.approvals.col_email"), "",
            ],
            "rows": [
                {
                    "cells": ["Sam Lin", "Engineering", "0912-345-678", "sam@example.com"],
                    "actions": [
                        {"label": _t("admin.approvals.approve"), "hotspot": True},
                        {"label": _t("admin.approvals.reject"), "danger": True},
                    ],
                },
            ],
        },
    },
    _nav_click_step(
        "bridge-invitations", "admin", _ADMIN_SUBNAV, _t("admin.nav.invitations"),
        "Click “" + _t("admin.nav.invitations") + "” in the admin tabs.",
    ),
    {
        "id": "admin-invitations-form",
        "track": "admin",
        "caption": "Invitations skip the whole approve/reject step: paste in "
                   "one or more emails, pick a starting level, and send.",
        "screen": "field_form",
        "screen_data": {
            "fields": [
                {"key": "admin.invitations.emails_label", "type": "textarea",
                 "value": "sam@example.com"},
                {"key": "admin.invitations.level_label", "type": "number", "value": "1"},
            ],
            "submit_key": "admin.invitations.send",
        },
    },
    {
        "id": "admin-invitations-result",
        "track": "admin",
        "caption": "Each address gets its own result line, so a typo in a "
                   "batch of twenty doesn't silently fail the other nineteen.",
        "screen": "list_panel",
        "screen_data": {
            "heading": _t("admin.invitations.result_title"),
            "items": [_t("admin.invitations.result_ok", email="sam@example.com")],
        },
    },
    {
        "id": "admin-invitations-outstanding",
        "track": "admin",
        "caption": "Every unused invitation stays visible and revocable until "
                   "it expires.",
        "screen": "table_list",
        "screen_data": {
            "heading": _t("admin.invitations.outstanding_title"),
            "columns": [
                _t("admin.invitations.col_email"), _t("admin.invitations.col_level"),
                _t("admin.invitations.col_status"), "",
            ],
            "rows": [
                {
                    "cells": ["sam@example.com", "1", _t("admin.invitations.status_valid")],
                    "actions": [{"label": _t("admin.invitations.revoke"), "hotspot": True, "danger": True}],
                },
            ],
        },
    },
    _nav_click_step(
        "bridge-members", "admin", _ADMIN_SUBNAV, _t("admin.nav.members"),
        "Click “" + _t("admin.nav.members") + "” in the admin tabs.",
    ),
    {
        "id": "admin-members-level",
        "track": "admin",
        "caption": "Levels drive preemption directly — raising someone's "
                   "level here is what lets them start overriding others.",
        "screen": "table_list",
        "screen_data": {
            "heading": _t("admin.members.title"),
            "columns": [
                _t("admin.members.col_name"), _t("admin.members.col_email"),
                _t("admin.members.col_level"), "",
            ],
            "rows": [
                {
                    "cells": [_COLLEAGUE, "alex@example.com", "3"],
                    "actions": [{"label": _t("admin.members.update_level"), "hotspot": True}],
                },
            ],
        },
    },
    {
        "id": "admin-members-suspend",
        "track": "admin",
        "caption": "Suspending blocks login immediately without touching "
                   "their history; the same button becomes \"Reactivate\" "
                   "once suspended.",
        "screen": "table_list",
        "screen_data": {
            "heading": _t("admin.members.title"),
            "columns": [_t("admin.members.col_name"), _t("admin.members.col_status"), ""],
            "rows": [
                {
                    "cells": [_COLLEAGUE, _t("status.active")],
                    "actions": [{"label": _t("admin.members.suspend"), "hotspot": True, "danger": True}],
                },
            ],
        },
    },
    {
        "id": "admin-delete-confirm",
        "track": "admin",
        "caption": "Deleting an account never erases it — it anonymizes the "
                   "person's details but keeps every booking, override and "
                   "audit record forever.",
        "screen": "confirm_dialog",
        "screen_data": {
            "title": _t("admin.members.delete.title"),
            "message": _t("admin.members.delete.confirm", name=_COLLEAGUE, email="alex@example.com"),
            "explain": _t("admin.members.delete.explain"),
            "note": _t("admin.members.delete.keeps_history"),
            "submit_label": _t("admin.members.delete.submit"),
            "cancel_label": _t("admin.members.delete.cancel"),
            "danger": True,
        },
    },
    {
        "id": "admin-delete-success",
        "track": "admin",
        "caption": "Done. Their name is gone from the record, but the "
                   "record itself stays.",
        "screen": "notice_panel",
        "screen_data": {"message": _t("admin.members.deleted", count=1), "kind": "success"},
    },
    _nav_click_step(
        "bridge-rooms", "admin", _ADMIN_SUBNAV, _t("admin.nav.rooms"),
        "Click “" + _t("admin.nav.rooms") + "” in the admin tabs.",
    ),
    {
        "id": "admin-rooms-list",
        "track": "admin",
        "caption": "Rooms are managed entirely in-app — no database access "
                   "needed to add one or take one out of service.",
        "screen": "table_list",
        "screen_data": {
            "heading": _t("admin.rooms.title"),
            "columns": [
                _t("admin.rooms.col_name"), _t("admin.rooms.col_capacity"),
                _t("admin.rooms.col_status"), "",
            ],
            "rows": [
                {
                    "cells": [_ROOM, "12", _t("admin.rooms.status_active")],
                    "actions": [
                        {"label": _t("admin.rooms.edit")},
                        {"label": _t("admin.rooms.deactivate"), "hotspot": True, "danger": True},
                    ],
                },
            ],
        },
    },
    {
        "id": "admin-rooms-confirm",
        "track": "admin",
        "caption": "Disabling a room with existing bookings doesn't happen "
                   "silently — it asks first and names exactly how many "
                   "meetings will be cancelled.",
        "screen": "confirm_dialog",
        "screen_data": {
            "title": _t("admin.rooms.confirm_title"),
            "message": _t("admin.rooms.confirm_body", name=_ROOM, count=3),
            "submit_label": _t("admin.rooms.confirm_button"),
            "cancel_label": _t("day.cancel_selection"),
            "danger": True,
        },
    },
    _nav_click_step(
        "bridge-closures", "admin", _ADMIN_SUBNAV, _t("admin.nav.closures"),
        "Click “" + _t("admin.nav.closures") + "” in the admin tabs.",
    ),
    {
        "id": "admin-closures-form",
        "track": "admin",
        "caption": "Closing part of a day, rather than a whole room. One "
                   "form covers a single afternoon or a six-week cleaning "
                   "slot: leave the end date blank for one day, and untick "
                   "Sat and Sun to close weekdays only.",
        "screen": "field_form",
        "screen_data": {
            "fields": [
                {"key": "admin.closures.field_room", "value": _ROOM},
                {"key": "admin.closures.field_from_date", "type": "date",
                 "value": "2026-08-15"},
                {"key": "admin.closures.field_to_date", "type": "date",
                 "value": "2026-10-01",
                 "help_key": "admin.closures.to_date_help"},
                {"key": "admin.closures.field_start_time", "value": "08:00"},
                {"key": "admin.closures.field_end_time", "value": "10:00"},
                {"key": "admin.closures.field_reason", "value": "Deep clean",
                 "help_key": "admin.closures.reason_help"},
            ],
            "submit_key": "admin.closures.create",
        },
    },
    {
        "id": "admin-closures-conflict",
        "track": "admin",
        "caption": "If meetings already sit inside the hours you are closing, "
                   "nothing happens yet — it stops and shows you which ones, "
                   "so you can move the closure instead. Confirming cancels "
                   "them and emails the people who booked them.",
        "screen": "confirm_dialog",
        "screen_data": {
            "title": _t("admin.closures.confirm_title"),
            "message": _t("admin.closures.confirm_body", count=2),
            "submit_label": _t("admin.closures.confirm_button"),
            "cancel_label": _t("day.cancel_selection"),
            "danger": True,
        },
    },
    {
        "id": "admin-closures-list",
        "track": "admin",
        "caption": "A date range stays one row, not one row per day, so a "
                   "seven-week closure is a single thing to read — and a "
                   "single Delete to call the whole thing off.",
        "screen": "table_list",
        "screen_data": {
            "heading": _t("admin.closures.title"),
            "columns": [
                _t("admin.closures.col_room"), _t("admin.closures.col_dates"),
                _t("admin.closures.col_time"), _t("admin.closures.col_weekdays"),
                _t("admin.closures.col_reason"), "",
            ],
            "rows": [
                {
                    "cells": [
                        _ROOM,
                        _t("admin.closures.date_range",
                           from_date="2026-08-15", to_date="2026-10-01"),
                        "08:00–10:00",
                        _t("common.list_separator").join(
                            _t(f"admin.closures.weekday_{d}") for d in range(5)
                        ),
                        "Deep clean",
                    ],
                    "actions": [
                        {"label": _t("admin.closures.delete"), "danger": True},
                    ],
                },
                {
                    "cells": [
                        _ROOM,
                        _t("admin.closures.single_day", date="2026-08-31"),
                        "12:00–15:00",
                        _t("admin.closures.every_day"),
                        "Maintenance",
                    ],
                    "actions": [
                        {"label": _t("admin.closures.delete"), "danger": True},
                    ],
                },
            ],
        },
    },
    _nav_click_step(
        "bridge-settings", "admin", _ADMIN_SUBNAV, _t("admin.nav.settings"),
        "Click “" + _t("admin.nav.settings") + "” in the admin tabs.",
    ),
    {
        "id": "admin-settings",
        "track": "admin",
        "caption": "Every rule that shapes booking and preemption — slot "
                   "size, max length, the override protection window, the "
                   "daily email cap — is a setting here, not a hardcoded "
                   "constant.",
        "screen": "field_form",
        "screen_data": {
            "fields": [
                {"key": "admin.settings.slot_minutes.label", "type": "number",
                 "value": "30", "help_key": "admin.settings.slot_minutes.help"},
                {"key": "admin.settings.max_booking_minutes.label", "type": "number",
                 "value": "240", "help_key": "admin.settings.max_booking_minutes.help"},
                {"key": "admin.settings.preemption_protection_minutes.label", "type": "number",
                 "value": "120", "help_key": "admin.settings.preemption_protection_minutes.help"},
                {"key": "admin.settings.daily_email_cap.label", "type": "number",
                 "value": "200", "help_key": "admin.settings.daily_email_cap.help"},
            ],
            "submit_key": "admin.settings.save",
        },
    },
    _nav_click_step(
        "bridge-bookings", "admin", _ADMIN_SUBNAV, _t("admin.nav.bookings"),
        "Click “" + _t("admin.nav.bookings") + "” in the admin tabs.",
    ),
    {
        "id": "admin-bookings-log",
        "track": "admin",
        "caption": "Every booking across every room and every member, in "
                   "one place, with a cancel action admins can use directly.",
        "screen": "table_list",
        "screen_data": {
            "heading": _t("admin.bookings.title"),
            "columns": [
                _t("admin.bookings.col_room"), _t("admin.bookings.col_owner"),
                _t("admin.bookings.col_start"), _t("admin.bookings.col_status"), "",
            ],
            "rows": [
                {
                    "cells": [_ROOM, "You", "14:00", _t("booking_status.confirmed")],
                    "actions": [{"label": _t("admin.bookings.cancel")}],
                },
            ],
        },
    },
    _nav_click_step(
        "bridge-preemptions", "admin", _ADMIN_SUBNAV, _t("admin.nav.preemptions"),
        "Click “" + _t("admin.nav.preemptions") + "” in the admin tabs.",
    ),
    {
        "id": "admin-preemptions-log",
        "track": "admin",
        "caption": "This is the one screen where the overriding member's "
                   "identity is shown — everywhere a member sees this "
                   "themselves (a BLOCKED message, an email), the other "
                   "party stays anonymous.",
        "screen": "table_list",
        "screen_data": {
            "heading": _t("admin.preemptions.title"),
            "columns": [
                _t("admin.preemptions.col_room"), _t("admin.preemptions.col_victim"),
                _t("admin.preemptions.col_winner"),
            ],
            "rows": [
                {"cells": [_ROOM, f"{_COLLEAGUE} ({_COLLEAGUE_DEPT})", "You (Engineering)"]},
            ],
        },
    },
    _nav_click_step(
        "bridge-emails", "admin", _ADMIN_SUBNAV, _t("admin.nav.emails"),
        "Click “" + _t("admin.nav.emails") + "” in the admin tabs.",
    ),
    {
        "id": "admin-emails-log",
        "track": "admin",
        "caption": "Every email the system tried to send, with its outcome — "
                   "this is also what backs the daily quota guard, which "
                   "drops reminder emails first if the cap is close. If "
                   "somebody deleted a message, Resend sends it again; a "
                   "failed one retries by itself.",
        "screen": "table_list",
        "screen_data": {
            "heading": _t("admin.emails.title"),
            "columns": [
                _t("admin.emails.col_type"), _t("admin.emails.col_to"),
                _t("admin.emails.col_status"), _t("admin.emails.col_actions"),
            ],
            "rows": [
                {
                    "cells": ["E4", "you@example.com", _t("admin.emails.status_sent")],
                    "actions": [{"label": _t("admin.emails.resend")}],
                },
                {
                    "cells": ["E5", "alex@example.com", _t("admin.emails.status_sent")],
                    "actions": [{"label": _t("admin.emails.resend")}],
                },
            ],
        },
    },
    _nav_click_step(
        "bridge-audit", "admin", _ADMIN_SUBNAV, _t("admin.nav.audit"),
        "Click “" + _t("admin.nav.audit") + "” in the admin tabs.",
    ),
    {
        "id": "admin-audit-log",
        "track": "admin",
        "caption": "One more log, separate from the override log and the "
                   "email log: a running record of every admin action across "
                   "the whole system — level changes, approvals, room edits, "
                   "setting changes — not just bookings and overrides.",
        "screen": "table_list",
        "screen_data": {
            "heading": _t("admin.audit.title"),
            "columns": [
                _t("admin.audit.col_actor"), _t("admin.audit.col_action"),
                _t("admin.audit.col_target"), _t("admin.audit.col_detail"),
            ],
            "rows": [
                {"cells": ["You", _t("admin.audit.action.level_changed"), _COLLEAGUE, "1 → 3"]},
                {"cells": ["You", _t("admin.audit.action.setting_changed"), "daily_email_cap", "150 → 200"]},
            ],
        },
    },
]

TUTORIAL_STEPS: list[dict] = [_resolve(step) for step in _RAW_STEPS]


#: Injected as an external same-origin file (`GET /tutorial.js`) so the
#: deployed page can load it under the site's CSP (`script-src 'self' ...`)
#: with no hash to maintain. The offline generator inlines this same string
#: instead, since a `file://` document has no CSP header to satisfy.
#:
#: No build step, no external libraries, no network calls -- mirrors the
#: constraints `app/web/enhance.py`'s SCRIPT already lives under.
TUTORIAL_SCRIPT = """
(function () {
  'use strict';

  var mount = document.getElementById('tutorial-mount');
  if (!mount) { return; }

  var dataEl = document.getElementById('tutorial-steps');
  var trackEl = document.getElementById('tutorial-track');
  if (!dataEl || !trackEl) { return; }

  var allSteps;
  try {
    allSteps = JSON.parse(dataEl.textContent);
  } catch (err) {
    return;
  }
  var defaultTrack = trackEl.textContent.trim();
  var reduceMotion = window.matchMedia &&
    window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  var state = { track: defaultTrack, index: 0 };

  function stepsForTrack(track) {
    return allSteps.filter(function (s) { return s.track === track; });
  }

  function el(tag, attrs, children) {
    var node = document.createElement(tag);
    attrs = attrs || {};
    for (var key in attrs) {
      if (!Object.prototype.hasOwnProperty.call(attrs, key)) { continue; }
      if (key === 'class') { node.className = attrs[key]; }
      else if (key === 'text') { node.textContent = attrs[key]; }
      else { node.setAttribute(key, attrs[key]); }
    }
    (children || []).forEach(function (child) { node.appendChild(child); });
    return node;
  }

  function hotspotButton(label, extraClass) {
    var cls = 'tutorial-hotspot' + (extraClass ? ' ' + extraClass : '');
    return el('button', { type: 'button', class: cls, text: label });
  }

  // A generic "move on" button used by screens with no real submit/action
  // of their own. Its label starts as "Continue" and render() corrects it
  // to "Finish" when this turns out to be a track's last step -- computed
  // once, centrally, rather than hand-marked on every screen (that's what
  // skipped whole sections of content the first time around: a step
  // wrongly authored as "last" jumped straight past everything after it).
  function navButton() {
    return hotspotButton('Continue', 'tutorial-nav-action');
  }

  function inertButton(label, extraClass) {
    var cls = extraClass ? extraClass : 'secondary';
    var btn = el('button', { type: 'button', class: cls, text: label });
    btn.disabled = true;
    return btn;
  }

  function renderFieldForm(data) {
    var wrap = el('div', { class: 'panel stack tutorial-screen' });
    if (data.notice) {
      wrap.appendChild(el('div', { class: 'notice notice-info', text: data.notice }));
    }
    var form = el('form', { class: 'stack' });
    data.fields.forEach(function (f) {
      var field = el('div', { class: 'field' });
      field.appendChild(el('label', { text: f.label }));
      var inputAttrs = { type: f.type === 'textarea' || f.type === 'number' ? f.type : f.type, disabled: 'disabled' };
      if (f.value) { inputAttrs.value = f.value; }
      if (f.type === 'textarea') {
        var ta = el('textarea', { disabled: 'disabled' });
        if (f.value) { ta.textContent = f.value; }
        field.appendChild(ta);
      } else {
        field.appendChild(el('input', inputAttrs));
      }
      if (f.help) { field.appendChild(el('small', { class: 'help', text: f.help })); }
      form.appendChild(field);
    });
    var actions = el('div', { class: 'actions' });
    actions.appendChild(hotspotButton(data.submit_label));
    form.appendChild(actions);
    wrap.appendChild(form);
    return wrap;
  }

  function renderNoticePanel(data) {
    var panel = el('div', { class: 'panel tutorial-screen' });
    panel.appendChild(el('div', {
      class: 'notice notice-' + (data.kind || 'info'), text: data.message,
    }));
    var actions = el('div', { class: 'actions' });
    actions.appendChild(navButton());
    panel.appendChild(actions);
    return panel;
  }

  function renderDayGridReadonly(data) {
    var panel = el('div', { class: 'panel stack tutorial-screen' });
    panel.appendChild(el('div', { class: 'notice notice-warning', text: data.banner }));
    var legend = el('div', { class: 'legend' });
    (data.legend || []).forEach(function (text) {
      legend.appendChild(el('span', { class: 'tag', text: text }));
    });
    panel.appendChild(legend);
    var actions = el('div', { class: 'actions' });
    actions.appendChild(navButton());
    panel.appendChild(actions);
    return panel;
  }

  function renderSlotList(slots) {
    var list = el('ul', { class: 'slot-list' });
    slots.forEach(function (slot) {
      var classes = ['slot'];
      if (slot.kind === 'mine') { classes.push('is-mine'); }
      if (slot.kind === 'other') { classes.push('is-booked'); }
      if (slot.kind === 'start') { classes.push('is-start'); }
      if (slot.kind === 'closed') { classes.push('is-closed'); }
      if (slot.kind === 'free' && slot.action_label) { classes.push('is-in-range'); }
      var detail = el('div', { class: 'slot-detail' });
      if (slot.kind === 'closed') {
        detail.appendChild(el('span', { class: 'slot-closed', text: slot.closed_label }));
        if (slot.detail) {
          detail.appendChild(el('span', { class: 'slot-owner', text: slot.detail }));
        }
      } else if (slot.detail) {
        detail.appendChild(el('span', { class: 'slot-title', text: slot.detail }));
      } else if (slot.kind === 'free') {
        detail.appendChild(el('span', { class: 'slot-free', text: 'Free' }));
      }
      var row = el('li', { class: classes.join(' ') }, [
        el('span', { class: 'slot-time', text: slot.time }),
        detail,
      ]);
      if (slot.action_label) {
        row.appendChild(hotspotButton(slot.action_label, 'slot-action'));
      }
      list.appendChild(row);
    });
    return list;
  }

  function renderDayGridInteractive(data) {
    var panel = el('div', { class: 'panel stack tutorial-screen' });
    panel.appendChild(el('p', { class: 'tutorial-hint', text: data.hint }));
    if (data.legend) {
      var legend = el('div', { class: 'legend' });
      data.legend.forEach(function (text) {
        legend.appendChild(el('span', { class: 'tag', text: text }));
      });
      panel.appendChild(legend);
    }
    panel.appendChild(el('h3', { text: data.room }));
    panel.appendChild(renderSlotList(data.slots));
    return panel;
  }

  function renderWarningBlock(warning) {
    var block = el('div', { class: 'confirm-panel' });
    block.appendChild(el('h2', { text: warning.title }));
    block.appendChild(el('p', { text: warning.message }));
    var list = el('ul', { class: 'victim-list' });
    (warning.victims || []).forEach(function (line) {
      list.appendChild(el('li', { text: line }));
    });
    block.appendChild(list);
    return block;
  }

  function renderBookingForm(data) {
    var panel = el('div', { class: 'panel stack tutorial-screen' });
    if (data.warning) {
      panel.appendChild(renderWarningBlock(data.warning));
    }
    var summary = data.summary;
    panel.appendChild(el('p', {
      text: summary.room + ' ・ ' + summary.time + ' (' + summary.duration + ')',
    }));
    panel.appendChild(el('p', { class: 'muted', text: data.change_time_label }));
    var form = el('div', { class: 'stack' });
    form.appendChild(el('p', { class: 'muted', text: data.pick_subject_label }));
    var chips = el('div', { class: 'chips' });
    data.presets.forEach(function (name) {
      chips.appendChild(el('button', { type: 'button', class: 'chip', disabled: 'disabled', text: name }));
    });
    form.appendChild(chips);
    var field = el('div', { class: 'field' });
    field.appendChild(el('label', { text: data.custom_label }));
    field.appendChild(el('input', { type: 'text', placeholder: data.custom_placeholder, disabled: 'disabled' }));
    form.appendChild(field);
    var actions = el('div', { class: 'actions' });
    actions.appendChild(hotspotButton(data.submit_label));
    form.appendChild(actions);
    panel.appendChild(form);
    return panel;
  }

  function renderConfirmDialog(data) {
    var panel = el('div', { class: 'confirm-panel' });
    if (data.title) { panel.appendChild(el('h2', { text: data.title })); }
    if (data.message) { panel.appendChild(el('p', { text: data.message })); }
    if (data.explain) { panel.appendChild(el('p', { text: data.explain })); }
    if (data.note) { panel.appendChild(el('p', { class: 'muted', text: data.note })); }
    if (data.victims) {
      var list = el('ul', { class: 'victim-list' });
      data.victims.forEach(function (line) { list.appendChild(el('li', { text: line })); });
      panel.appendChild(list);
    }
    var actions = el('div', { class: 'actions' });
    actions.appendChild(hotspotButton(data.submit_label, data.danger ? 'danger' : ''));
    actions.appendChild(el('button', { type: 'button', class: 'secondary', text: data.cancel_label }));
    panel.appendChild(actions);
    return panel;
  }

  function renderListPanel(data) {
    var panel = el('div', { class: 'panel stack tutorial-screen' });
    panel.appendChild(el('h3', { text: data.heading }));
    var list = el('ul');
    data.items.forEach(function (text) { list.appendChild(el('li', { text: text })); });
    panel.appendChild(list);
    var actions = el('div', { class: 'actions' });
    actions.appendChild(navButton());
    panel.appendChild(actions);
    return panel;
  }

  function renderDashboardPanel(data) {
    var panel = el('div', { class: 'panel stack tutorial-screen' });
    panel.appendChild(el('h3', { text: data.title }));
    data.stats.forEach(function (stat) {
      var row = el('p');
      row.appendChild(el('strong', { text: stat.label + ': ' }));
      row.appendChild(document.createTextNode(stat.value));
      panel.appendChild(row);
    });
    var actions = el('div', { class: 'actions' });
    actions.appendChild(navButton());
    panel.appendChild(actions);
    return panel;
  }

  function renderTableList(data) {
    var panel = el('div', { class: 'stack tutorial-screen' });
    panel.appendChild(el('h3', { text: data.heading }));
    var table = el('table', {}, [
      el('thead', {}, [
        el('tr', {}, data.columns.map(function (c) { return el('th', { text: c }); })),
      ]),
    ]);
    var tbody = el('tbody');
    var hasHotspotRowAction = false;
    data.rows.forEach(function (row) {
      var tds = row.cells.map(function (cell) { return el('td', { text: cell }); });
      if (row.status) {
        tds.push(el('td', {}, [
          el('span', { class: 'tag ' + (row.status.tag_class || ''), text: row.status.text }),
        ]));
      } else if (row.actions) {
        var actionButtons = row.actions.map(function (a) {
          if (a.hotspot) { hasHotspotRowAction = true; }
          var cls = (a.hotspot ? 'tutorial-hotspot ' : '') + (a.danger ? 'danger' : 'secondary');
          var btn = el('button', { type: 'button', class: cls.trim(), text: a.label });
          if (!a.hotspot) { btn.disabled = true; }
          return btn;
        });
        tds.push(el('td', {}, actionButtons));
      }
      tbody.appendChild(el('tr', {}, tds));
    });
    table.appendChild(tbody);
    panel.appendChild(el('div', { class: 'table-wrap' }, [table]));
    if (!hasHotspotRowAction) {
      var actions = el('div', { class: 'actions' });
      actions.appendChild(navButton());
      panel.appendChild(actions);
    }
    return panel;
  }

  function renderHeaderPreview(data) {
    var panel = el('div', { class: 'panel stack tutorial-screen' });
    var bar = el('div', { class: 'bar' });
    bar.appendChild(el('span', { class: 'brand', text: data.brand }));
    var navEl = el('nav', { class: 'site-nav' });
    var ul = el('ul');
    data.nav_items.forEach(function (label) {
      ul.appendChild(el('li', {}, [inertButton(label)]));
    });
    ul.appendChild(el('li', {}, [
      inertButton(data.admin_item + ' (admin only)', 'secondary'),
    ]));
    navEl.appendChild(ul);
    bar.appendChild(navEl);
    bar.appendChild(el('span', { class: 'account-name', text: data.account_name }));
    bar.appendChild(inertButton(data.logout_label));
    bar.appendChild(el('span', { class: 'muted', text: '🌐 ' + data.language_label }));
    panel.appendChild(el('header', { class: 'site-header' }, [bar]));
    var actions = el('div', { class: 'actions' });
    actions.appendChild(navButton());
    panel.appendChild(actions);
    return panel;
  }

  function renderDayOverview(data) {
    var panel = el('div', { class: 'panel stack tutorial-screen' });
    var dateBar = el('div', { class: 'date-bar' });
    dateBar.appendChild(inertButton(data.prev_label));
    dateBar.appendChild(inertButton(data.today_label));
    dateBar.appendChild(el('span', { class: 'muted', text: data.date_label }));
    dateBar.appendChild(inertButton(data.next_label));
    panel.appendChild(dateBar);
    var legend = el('div', { class: 'legend' });
    data.legend.forEach(function (text) {
      legend.appendChild(el('span', { class: 'tag', text: text }));
    });
    panel.appendChild(legend);
    var jump = el('details', { class: 'jump', open: 'open' });
    jump.appendChild(el('summary', { text: data.jump_label }));
    var jumpList = el('ul', { class: 'jump-list' });
    data.rooms.forEach(function (room) {
      jumpList.appendChild(el('li', {}, [el('span', { text: room.name })]));
    });
    jump.appendChild(jumpList);
    panel.appendChild(jump);
    var grid = el('div', { class: 'day-grid cols-3' });
    data.rooms.forEach(function (room) {
      var col = el('div', { class: 'room-column' });
      col.appendChild(el('h3', { text: room.name }));
      col.appendChild(renderSlotList(room.slots));
      grid.appendChild(col);
    });
    panel.appendChild(grid);
    var actions = el('div', { class: 'actions' });
    actions.appendChild(navButton());
    panel.appendChild(actions);
    return panel;
  }

  function renderNavClick(data) {
    var panel = el('div', { class: 'panel tutorial-screen' });
    var navEl = el('nav', { class: 'site-nav' });
    var ul = el('ul');
    data.items.forEach(function (item) {
      var control = item.hotspot ? hotspotButton(item.label) : inertButton(item.label);
      ul.appendChild(el('li', {}, [control]));
    });
    navEl.appendChild(ul);
    panel.appendChild(navEl);
    return panel;
  }

  var RENDERERS = {
    field_form: renderFieldForm,
    notice_panel: renderNoticePanel,
    day_grid_readonly: renderDayGridReadonly,
    day_grid_interactive: renderDayGridInteractive,
    booking_form: renderBookingForm,
    confirm_dialog: renderConfirmDialog,
    list_panel: renderListPanel,
    dashboard_panel: renderDashboardPanel,
    table_list: renderTableList,
    header_preview: renderHeaderPreview,
    day_overview: renderDayOverview,
    nav_click: renderNavClick,
  };

  function advance() {
    var steps = stepsForTrack(state.track);
    if (state.index < steps.length - 1) {
      state.index += 1;
      render();
    }
  }

  function back() {
    if (state.index > 0) {
      state.index -= 1;
      render();
    }
  }

  var trackToggleButtons = document.querySelectorAll('.tutorial-track-toggle');

  // Keeps the two track buttons' own appearance in sync with state.track --
  // without this, clicking one only ever changed the content below, never
  // the buttons themselves, so there was no way to tell which was active.
  function updateTrackToggles() {
    trackToggleButtons.forEach(function (btn) {
      var isActive = btn.dataset.track === state.track;
      btn.setAttribute('aria-pressed', isActive ? 'true' : 'false');
      if (btn.disabled) { return; }
      if (isActive) {
        btn.classList.add('is-active');
        btn.classList.remove('secondary');
      } else {
        btn.classList.remove('is-active');
        btn.classList.add('secondary');
      }
    });
  }

  function setTrack(track) {
    if (!stepsForTrack(track).length) { return; }
    state.track = track;
    state.index = 0;
    updateTrackToggles();
    render();
  }

  function render() {
    var steps = stepsForTrack(state.track);
    var step = steps[state.index];
    mount.innerHTML = '';
    if (!step) { return; }

    var wrapper = el('div', {
      class: 'tutorial-step' + (reduceMotion ? '' : ' tutorial-animate'),
    });
    wrapper.appendChild(el('p', { class: 'tutorial-progress',
      text: 'Step ' + (state.index + 1) + ' of ' + steps.length }));
    wrapper.appendChild(el('p', { class: 'tutorial-caption', text: step.caption }));

    var renderer = RENDERERS[step.screen];
    if (renderer) {
      wrapper.appendChild(renderer(step.screen_data));
    }

    var isLast = state.index === steps.length - 1;
    var navAction = wrapper.querySelector('.tutorial-nav-action');
    if (navAction) {
      navAction.textContent = isLast ? 'Finish' : 'Continue';
    }

    var nav = el('div', { class: 'tutorial-nav' });
    var backBtn = el('button', { type: 'button', text: 'Back' });
    backBtn.disabled = state.index === 0;
    backBtn.addEventListener('click', back);
    nav.appendChild(backBtn);
    wrapper.appendChild(nav);

    mount.appendChild(wrapper);

    var hotspot = wrapper.querySelector('.tutorial-hotspot');
    if (hotspot) {
      if (isLast) {
        hotspot.disabled = true;
      } else {
        hotspot.classList.add(reduceMotion ? '' : 'tutorial-pulse');
        hotspot.addEventListener('click', advance);
      }
    }
  }

  trackToggleButtons.forEach(function (btn) {
    if (btn.disabled) { return; }
    btn.addEventListener('click', function () { setTrack(btn.dataset.track); });
  });

  updateTrackToggles();
  render();
})();
"""
